[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer-runs = 1000
solc-version = "0.8.24"

remappings = [
    "@prb/math@4.0.2/=lib/prb-math/",
    "@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
gnosis-mainnet = "https://gnosis-rpc.publicnode.com"
chiado-testnet = "https://rpc.chiadochain.net"

[fuzz]
seed = "0x544D"

[invariant]
runs = 256
